- name: Ansible LAMP Install
  hosts: ubuntu
  become: yes
  tasks:
    - name: Ansible apt to install multiple packages
      register: updatesys
      apt:
        update_cache: yes
        name:
          - firewalld
          - apache2
          - mariadb-server
          - php
          - php-mysql
        state: present
